### ISSUE TITLE
Yarn fails to install from github directly - Module not found: Can't resolve '@ethersphere/bee-js'

### ISSUE THREAD

**Issue by wendydv1989** [ethersphere/bee-js#162]
Made a clean create-react-app.
Added bee-js with yarn add 
Added import in App.js
Yarn start: Can't resolve '@ethersphere/bee-js'

**Comment by vojtechsimetka** [comment]
Do you have a source code to share? Can you send exactly the commands you used?

**Comment by vojtechsimetka** [comment]
Just tried and it works. Which version of `yarn` and `nodejs` are you using? https://github.com/vojtechsimetka/cra-yarn-bee-js.

Tested with:
```
yarn 1.22.10
nodejs v14.15.4
```

Steps:
```
npx create-react-app yarn-test    

cd yarn-test

yarn add @ethersphere/bee-js --save
```
Imported and instantiated in `src/App.js`
https://github.com/vojtechsimetka/cra-yarn-bee-js/commit/9217200e36585e966105bc953cbe04e150017733#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R1-R9

**Comment by wendydv1989** [comment]
I'm trying with "@ethersphere/bee-js": "github:ethersphere/bee-js#release-v0.5.1",

**Comment by AuHau** [comment]
This might be the reason: https://github.com/yarnpkg/yarn/issues/5235#issuecomment-571206092

**Comment by vojtechsimetka** [comment]
Ah yeah that is probably it. After reading the comments this seems to be a workaround for yarn `v1.x` but is fixed in `v2.x` and will NOT be backported to `v1.x`.

So the decision is - do we want to pollute even more our root folder with specific fix for older versions of yarn? Or de we just document that those who want to install from github should use either npm or yarn `v2.x`? I prefer the second.

**Comment by agazso** [comment]
> So the decision is - do we want to pollute even more our root folder with specific fix for older versions of yarn? Or de we just document that those who want to install from github should use either npm `v6.x` or yarn `v2.x` or newer? I prefer the second.

I vote for the second: document and use v2.x or newer.

**Comment by AuHau** [comment]
Hmm, I am not so sure about "dropping support for yarn 1" because of this rather edge case. I was bit reading up on Yarn 2 and it seems that it is not that much widely accepted by the community as it introduced a new way of dependency management that apparently broke some things.

Maybe only a note about this to Install section of Readme?
