### ISSUE TITLE
Feed's topic is not limited to 32 bytes

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#200]
Was looking into what is the limitation of topics as I was a bit confused by API docs and it turned out that the topic is not limited to any specific size and the API only need it hex encoded. It is then internally hashed with the index inside Bee, so that's why.

In code, we have on several places mentioned that the topic is limited to 32 bytes, maybe with some runtime checks as well.

I would therefore propose to remove those. Maybe drop the `makeTopicFromString()` helper as well?

**Comment by agazso** [comment]
Please check first with the Bee team what is the correct type. In the Book of Swarm it is defined as 32 bytes (pg. 109, 4.3.1) and in Swarm historically it was 32 bytes. Also the PSS topic is defined as 32 bytes, maybe not coincidentally. It is possible that the feed implementation in Bee is not complete and does not check the size of the topic.

https://gateway.ethswarm.org/bzz/latest.bookofswarm.eth/

The `makeTopicFromString` is orthogonal to this, it's there so that the users do not have to deal with hex strings. However if the topic is not limited to 32 bytes we can replace the hash function to a simple hex conversion.

**Comment by AuHau** [comment]
Well, you are right that 32 bytes are limit to the SOC Identifier, but for Feeds that is got from hashing the topic and index and thanks to that those can be "anything". Actually, I found the same code in bee-js as well: https://github.com/ethersphere/bee-js/blob/78971637c9e9286a232456dfd953e69f32132e2d/src/feed/index.ts#L73

**Comment by AuHau** [comment]
Currently, the topic is Bee-js is enforced to 32 bytes and if users need arbitrary topic, then he can use the `makeFeedTopic`, so I am closing this.
