### ISSUE TITLE
Input validation of exposed funtions/methods

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#202]
**Rationale**
As a developer and user of bee-js I would like to be alerted if I am using the functionality wrong = passing not supported or unexpected values. While we can not guarantee that the usage is correct, we can at least limit the potential wrongs by thorough type checking. This will also likely catch at least some security issues like passing functions that are evaluated in the code.

**Task**
Review all the exposed functions and methods and ensure all inputs are validated

**Concerns**
Argument: _Computation overhead_
Response: Type checking is generally not all that resource intensive (we are talking couple of instructions) if done right. Also, I assume most of the functions in `bee-js` are not going to be frequently invoked (e.g. at most every few seconds) so this validation code will not be run frequently.

**Comment by nugaon** [comment]
In my opinion, the array checking - especially in case of big sized arrays - we shouldn't check _every_ element of the object in question.
E.g. https://github.com/ethersphere/bee-js/blob/a88277db374b3bafe273614954d43afad72018e8/src/utils/data.ts#L20
While you may be right about these functions won't be called frequently (though there could be a use-case always where this statement is false) these computational overheads don't yield better UX experience, because they seem like wasteful operations.
Nevertheless I support the idea the check every passed parameters in this reasonable sense.
Would be nice, if the PR which resolves this issue, also would fix #143 as well

**Comment by AuHau** [comment]
Concrete problem as reported by @nugaon:

>I got 500 error on file upload if I pass File type (without array) for fileList parameter of uploadFile
It awaits array of files, but it does not check whether the user input is correct or not.

Moved here from: https://github.com/ethersphere/bee-js/issues/243
