### ISSUE TITLE
Append Extra Headers for All BeeJS requests

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#251]
If there is a `proxy` between the dApp and the Bee client, the requests would require additional headers.

At Bee class initialization, there should be an optional `extraHeaders` parameter, where user can define these specific headers for their needs. It has to apply on all outgoing request from Bee instance.

**Comment by AuHau** [comment]
I have started to work on this, but I think this will be more tricky than it seems. Mainly because it requires setting up a structure on how to pass "global options" around. 

Until now all the modules only required to have passed `url` parameter which was the only "global" parameter and IMO very sensible thing to do in the current way, but now with introducing this `extraHeaders` option that is another parameter that has to be passed through the whole stack all the way to the lowest bottom of the `axios` call and this brings a question if some more sophisticate way should be introduced for this concept in order to make it scalable.

There are few approaches I can think of:

 - Use `axios.defaults` which would not need to pass any parameters around, but it is a global setting and does not work with having multiple instances of `Bee` class (only applicable to this issue, not a "global parameters" solution)
 - Have `context` object passed as a parameter in all modules that would contain these "global" options. (Question: should we refactor the `url` parameter to be part of it?)
 - Use closures. This would be a big change to the internal structure, but for example this is the way how js-ipfs structure its code. See for example [here](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/add.js#L15).

What are you thoughts? @ethersphere/js

**Comment by nugaon** [comment]
as we discussed on the stand-up, we are going with the first one, by providing utility function to modify axios request headers globally on requests.
