### ISSUE TITLE
Accounting APIs return `number` and not `bigint` types In browsers

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#291]
Tested in Brave, Chrome and Safari.

Here is an example code https://github.com/ethersphere/examples-js/tree/test/browser-bigint/acccounting-test

**Comment by agazso** [comment]
I did some investigation and it seems that the root cause of the problem is that axios uses the [XMLHttpRequest API](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) in the browser, which returns an `object` when the returned response's type is `json`. 

See documentation here: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response

The code in the [transform function](https://github.com/ethersphere/bee-js/blob/6e104dca1f1da4fb9713789854bc1b4ea31cefef/src/utils/safeAxios.ts#L79) expects a string response to do the BigInt transformation, it never runs and just returns the data object instead. On the other hand it doesn't matter at this point, because the conversion from the response to `object` already happened _incorrectly_ in the XHR request, even before the data is passed to the transformer function.

To me it's not yet clear what's the best way to proceed with this problem. The cleanest solution would be to [change the Bee API to return strings instead of numbers](https://github.com/ethersphere/bee/issues/1561) for monetary values, because then there is no need to work around the limitations of the XHR API, it would work correctly everywhere and users of the API could decide how to deal with the BigInts and conversions.

As a workaround it may be possible to disable or modify the default behavior of the XHR API, as the response documentation page suggests:

> You may attempt to request the data be provided in a specific format by setting the value of responseType after calling open() to initialize the request but before calling send() to send the request to the server.

But I am not sure this would lead to a solution that would reliably work across different browsers and would not complicate the code too much for the sake of a workaround.

**Comment by AuHau** [comment]
Thanks for the research! But I am not sure if your asse
