### ISSUE TITLE
Remove tar-stream and use in-memory tar for better browser support

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#32]

**Comment by AuHau** [comment]
Not sure what exactly you are planning here and how you plan to implement it, but I would advise avoiding in-memory operation if possible. Yes, in the browser this is most probably not possible, but for the Node environment, this is crucial, because imagine you are uploading ten 1GB files, then you would have to allocate 10 GB in your memory which is something that might not even be possible.

I was dealing with lot of these problems when I was working on RIF Storage.js and back then trying to use Erebos library, which in the end I "forked" into a separate "library" that I did not get around to really release: https://github.com/rsksmart/rif-storage-js/tree/master/src/swarm-mini

I saw your PR #28 and mentioning the Browser environment. In the old Swarm implementation this was possible to be solved using the FormData (hence [Vojtech's comment I believe](https://github.com/ethersphere/bee-js/pull/28#discussion_r540142203)) without actually needing the `tar-stream`. That one was used only for download, which browser is capable of supporting streaming download. I am not sure if Bee supports it?

Few pointers:
 - Preparation of upload for NodeJS: https://github.com/rsksmart/rif-storage-js/blob/master/src/swarm-mini/utils/data.ts
 - Preparation of upload for browser: https://github.com/rsksmart/rif-storage-js/blob/master/src/swarm-mini/utils/data.browser.ts

Just FYI :-)

**Comment by vojtechsimetka** [comment]
Thanks for your feedback @AuHau. You are right of course and we know this is not a long term solution. But we want to move fast and release as soon as possible. So we decided it is better to implement simple (less efficient) solution right now that will cover most usecases and then come back and optimize it.

We also decided that we want to as much as possible utilise browser native functions and then polyfill them on nodejs. This should result in smaller bundle size on browser which is much more important than on nodejs.

**Comment by AuHau** [comment]
Sure, no prob. Btw. FormData exactly meets your approach ;-)

**Comment by agazso** [comment]
The idea is that as a first step we would like to make hosting websites and applications on Swarm easy. For that milestone we don't aim to support 1GB sized files but rather in the ballpark of 10-100MB, so storing the files and creating the tar file in memory is good enough.

Later we plan to support different user-stories where we would want to enable storing bigger files. We will implement proper streaming functionality by then even in the browser.

This is indeed a change in our approach because we want to provide as much functionality in the browser as possible. Therefore we plan to support browser based APIs first and then try to provide polyfills for node.js instead of doing the other way. The reason for this is that we would like to keep the bundle for the browser rather small, whereas for node.js applications the size doesn't matter as much. On the other hand this means that we might need to change the existing libraries because most of them are built for node.js so this may take a little longer.

As an example of this approach take a look at this library:
https://github.com/MattiasBuelens/web-streams-polyfill
