### ISSUE TITLE
Tags are automatically created - should we automatically return them?

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#366]
All the upload endpoints upon successful upload automatically create a Tag that is returned in the response header `Swarm-Tag`. 

Currently, we return only the reference but should we return the object instead with both values?

**Comment by agazso** [comment]
Originally this was the motivation behind returning object types with a reference property in it: so that it can be extended with information about other things, for example tags. 

I can imagine some possible ways forward:
- Change back to return response object including tags. This would be a breaking change and make the most common operation (to get the reference) a bit more complicated.
- Add alternative functions that would return an object including the tags. That would pollute the `Bee` class and could introduce duplication making maintenance more difficult.
- Add a flag that would change the behavior of the existing function to return an object with tags instead of a reference. Not sure this can be done easily with Typescript though.
- Extend the `Reference` type (or whatever we return) with a tag property. This is a similar hack that we did with `Data`.

**Comment by AuHau** [comment]
> Extend the Reference type (or whatever we return) with a tag property. This is a similar hack that we did with Data.

I originally thought that it might not be possible since it is a `string`, but I just tried it and it is possible, but I would still avoid it as I think it will create more problems as for example `console.log` on such an object does not return the string etc.

> Change back to return response object including tags. This would be a breaking change and make the most common operation (to get the reference) a bit more complicated.

Since we gonna have a breaking release we could maybe incorporate this change in this fashion?

**Comment by agazso** [comment]
> I originally thought that it might not be possible since it is a `string`, but I just tried it and it is possible, but I would still avoid it as I think it will create more problems as for example `console.log` on such an object does not return the string etc.

I agree, it's a hack and it can be also confusing to explain it in the docs.

> > Change back to return response object including tags. This would be a breaking change and make the most common operation (to get the reference) a bit more complicated.
> 
> Since we gonna have a breaking release we could maybe incorporate this change in this fashion?

That seems the most straightforward option anyhow so let's do it.
