### ISSUE TITLE
Exposing SOC and Feed APIs on the Bee class

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#71]
When working on the Single Owner Chunk PR (#69) I realized that there are multiple ways of exposing the SOC API (and the Feed API after that) and there are different tradeoffs with the different solutions. Here I would like to present the alternatives that I came up with to discuss these aforementioned tradeoffs and to hopefully come up with a better solution.

The root problem is that the interface of the SOC API is asymmetric when uploading and downloading regarding the need of a signer object. When uploading an SOC it has to be signed already, so an implementation of the `Signer` interface must be passed to the upload function. The implementation of the `Singer` may be complicated because it may involve integration  with 3rd party libraries and applications that are security critical because they must store a private key and on behalf of the user are supposed to sign data (transactions in the case of Ethereum and chunks in the case of Swarm). While there is a default singer implementation provided for convenience, it expects the privateKey to be passed in directly which may not be a good idea to encourage the users from a security perspective.

Also one may imagine many use-cases when an application only wants to download data and never upload, or at least never upload signed content. In these cases it would be better if the user weren't forced to provide a `Signer` object. However when downloading in order to calculate the chunk address we need the ethereum account address (which is provided by the `Signer` interface by the way).

With that said here are the alternatives I came up with so far:

1. Expose upload and download as class functions on Bee:

This would look like the following:
```typescript
uploadSingleOwnerChunk(signer: Singer, identifier: Identifier, data: Uint8Array, options?: UploadOptions): Promise<BeeResponse>
downloadSingleOwnerChunk(ownerAddress: EthAddress, identifier: Identifier): Promise<SingleOwnerChunk>
```

Pros:
- simplicity from the implementation standpoint, it is very similar how the other API endpoints are exposed
- download doesn't need the signer interface, only the ethereum address

Cons:
- the user is supposed to keep track of which address and identifier is used for uploading and downloading because there is no interface holding that information

2. Expose signed Bee class for providing operations that require signing

```typescript
class Bee {
  // ...details are omitted
  withSigner(signer: Signer): BeeWithSigner
}

class BeeWithSigner {
  uploadSOC(identifier: Identifier, data: Uint8Array, options?: UploadOptions): Promise<BeeResponse>
  downloadSOC(identifier: Identifier): Promise<SingleOwnerChunk>
}
```

Pros:
- the user only need to instantiate a `BeeWithSigner` (name is up for discussion) object and upload and download happens with the same owner automatically

Cons:
- for download the Signer interface is not necessary (see above)

3. Expose semantic objects for providing operations that require signing

```typescript
// name shortened for brevity
interface SOCProvider {
  readonly identifier: Identifier
  upload(signer: Signer, data: Uint8Array, options?: UploadOptions): Promise<BeeResponse>
  download(ownerAddress: EthAddress): Promise<SingleOwnerChunk>
}

class Bee {
  // ...details are omitted
  soc(identifier: Identifier): SOCProvider
}

```

Pros:
- at least the `identifier` is stored in the Provider object so the user doesn't need to keep track of that
- download doesn't need the signer interface, only the ethereum address

Cons:
- the naming should be improved, for example Provider is too generic to be intuitively understandable to use
- there are schemes (for example Feeds) where the identifier changes with each update so it seems a bit extraneous to create a soc object every time the user want to update. Or when looking up it would need to create multiple providers (assuming Feeds would use this API)

@nugaon 
@vojtechsimetka 
This is my current state of mind, I would like to hear your ideas, preferences and feedback on this topic.

**Comment by nugaon** [comment]
I would say the optimal solution could be from the mixture of that you listed up.
we should keep from the 1st to provide asymetric invocation for download and upload, because most of the use-cases in applications utilize either one of these functions but rarely both.
The 2nd is good in provide a clear distinction for signer required swarm services(, although as you mentioned the download doesn't need full-featured signer init)
The 3rd seems closer to that perspective that the 2nd solution would like to reach. Along with the cons that you referred, it doesn't pack all Swarm functionalities within one `Bee` class that was our intention to do and also doesn't seem really intuitive to use.

What would be, if on Bee initialization optionally I could pass parameters to instantiate Signer object, that the Bee constructor could handle.
Let's say I pass `new Bee('http://localhost:1633', { signer: { sign, address } })` where the second parameter is optional and its `signer` property is needed for init `Signer`, that the `Bee` could use later if there is need for it.
Also there would be nice to have a helper function for add or modify later the `Signer` of the `Bee` instance. 
The params of `uploadSingleOwnerChunk` method would be then `(identifier: Identifier, data: Uint8Array, options?: UploadOptions)`.
`ownerAddress: EthAddress` of `downloadSingleOwnerChunk` could be optional with default of the `Signer` object's Ethereum address if it presents. 
On calling `uploadSingleOwnerChunk` within Bee instance which wasn't inited with Signer params (or wasn't added before the calling this method) simply throws an Error with message it lacks of defined signer object.

**Comment by agazso** [comment]
> we should keep from the 1st to provide asymetric invocation for download and upload, because most of the use-cases in applications utilize either one of these functions but rarely both.

I am not sure this is true, for example Feed update requires both: lookup uses several downloads to figure out the next insertion position, then inserting is an upload.

> The 3rd seems closer to that perspective that the 2nd solution would like to reach. Along with the cons that you referred, it doesn't pack all Swarm functionalities within one `Bee` class that was our intention to do and also doesn't seem really intuitive to use.

In my understanding it was never the goal to "pack" all functionalities within one Bee class (otherwise I would have chosen the first option automatically) but to be able to access all functionality from the Bee class. I think all the three options provide that.

> What would be, if on Bee initialization optionally I could pass parameters to instantiate Signer object, that the Bee constructor could handle.
> Let's say I pass `new Bee('http://localhost:1633', { signer: { sign, address } })` where the second parameter is optional and its `signer` property is needed for init `Signer`, that the `Bee` could use later if there is need for it.
> Also there would be nice to have a helper function for add or modify later the `Signer` of the `Bee` instance.
> The params of `uploadSingleOwnerChunk` method would be then `(identifier: Identifier, data: Uint8Array, options?: UploadOptions)`.
> `ownerAddress: EthAddress` of `downloadSingleOwnerChunk` could be optional with default of the `Signer` object's Ethereum address if it presents.
> On calling `uploadSingleOwnerChunk` within Bee instance which wasn't inited with Signer params (or wasn't added before the calling this method) simply throws an Error with message it lacks of defined signer object.

I also considered this option but I chose to decide against it because of the following reasons:
- The `Signer` is optional on `Bee` but can cause runtime error if not provided for certain operations. I would prefer to have optional constructor arguments to be optional, that is if you provide them then they change some behavior but if you don't provide them then a default behavior would happen (which is not an error).
- What's even worse the callsite where the error happens (`upload`) is different where you provide the argument (`constructor`). This makes errors harder to find in a bigger application. I think a good API is design is one where the provided arguments can be checked when a function is called.
- Because of the above I'm generally against making the `Bee` class stateful, so I wouldn't add helper methods to add or modify an existing instance.

**Comment by agazso** [comment]
There is another alternative (as seen in [erebos](https://erebos.js.org)):

Have a separate `Reader` and `Writer` interface where `Writer extends Reader`. 

```typescript
interface SOCReader {
  download: (identifier: Identifier) => Promise<SingleOwnerChunk>
}

interface SOCWriter extends SOCReader {
  upload: (identifier: Identifier, data: Uint8Array, options?: UploadOptions): Promise<BeeResponse>
}

class Bee {
  // ...
  makeSOCReader(ownerAddress: EthAddress): SOCReader
  makeSOCWriter(signer: Signer): SOCWriter
}
```

What do you think?

**Comment by nugaon** [comment]
> In my understanding it was never the goal to "pack" all functionalities within one Bee class (otherwise I would have chosen the first option automatically) but to be able to access all functionality from the Bee class. I think all the three options provide that.

I meant to directly use functionalities via Bee class that the Bee-client can provide and don't utilize its services through returned functions and handle variables in it that it will utilize.

> I am not sure this is true, for example Feed update requires both: lookup uses several downloads to figure out the next insertion position, then inserting is an upload.

that's why it could be a problem to provide functions outside of the Bee class, because the functions' scope change, later other functions can came into the picture that also require signer object and also you cannot use optional fallbacks to signer object (for example use its public address) on functions that are not closely signer related functions.

> - The Signer is optional on Bee but can cause runtime error if not provided for certain operations. I would prefer to have optional constructor arguments to be optional, that is if you provide them then they change some behavior but if you don't provide them then a default behavior would happen (which is not an error).
> - What's even worse the callsite where the error happens (upload) is different where you provide the argument (constructor). This makes errors harder to find in a bigger application. I think a good API is design is one where the provided arguments can be checked when a function is called and if they are invalid an error is returned immediately.

The goal is noble, but still I think it makes the usage more complex and inconvenient in general, in terms of passing always signer objects to signer related functions, handle Bee related variables outside of Bee class.

In regard to dinamic errors, I don't think it would be hard to trace back with throwing a well written errors as so far accomplished.

> Because of the above I'm generally against making the Bee class stateful, so I wouldn't add helper methods to add or modify an existing instance.

well, that's also a viewpoint, which have the same downside that I mentioned regards to the convenient usage, but I agree it is more tangible in a way that you say and it rules out wrong usage during the lifetime of the Bee instace.

**Comment by AuHau** [comment]
I agree with @nugaon on his approach. That was my idea for that approach as well. I think a lot of use cases will use only one `Signer` (eq. wrapped Metamask etc.) during the app's lifecycle, so I think it would make more sense to allow to have default signer binded to the class's instance.

This could then simplify the Feed's API as well.

Btw. Bee class is already stateful because it holds `url`.
