### ISSUE TITLE
Downloading file containing only string throws exception

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#86]
The most basic example we have in README does not work:

```
const bee = new Bee("http://localhost:1633");

const fileHash = await bee.uploadFile("Bee is awesome!");
const retrievedData = await bee.downloadFile(fileHash);

console.log(retrievedData.toString()); // prints 'Bee is awesome!'
```

It throws:
```
Uncaught (in promise) Error: missing content-disposition header
    at readContentDispositionFilename (headers.ts:26)
    at readFileHeaders (headers.ts:39)
    at Object.download (file.ts:68)
    at async handleSubmit (App.tsx:20)
```

The same happens if I use `uploadData` and `downloadData`

**Comment by agazso** [comment]
Ok, there are a few things going on here :)

1. In the README we should use `uploadData` and `downloadData` because we are not working with files. I don't even think anymore that it's a good idea that the `filename` argument is optional on the `uploadFile` call but that's how the Bee API works and I just copied the API.
2. A `GET` request from the `/files` endpoint (what `downloadFile` is doing) always returns a `content-disposition` header. It's possible that for some reason the header is missing, for example it's not allowed by CORS. See this:
https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields
Can you please verify that this is the case in the browser with the help of the Developer tools?
3. `downloadData` does not check the `content-disposition` header so it should work. Can you please verify?

We even have a [test for this case](https://github.com/ethersphere/bee-js/blob/ffb69519a71b62b8fd121a51b88f1a5e581dc15d/test/modules/file.spec.ts#L19) but the lesson is that we should somehow run these tests in the browser as well to make sure they really work.

**Comment by vojtechsimetka** [comment]
Just for record: `uploadData` and `downloadData` works. The issue with `uploadFile` and `downloadFile` is demonstrated in https://github.com/vojtechsimetka/bee-js-ui-demo/blob/test/uploadFile/src/App.tsx#L21-L28

**Comment by agazso** [comment]
I managed to verify that it is indeed due to CORS, more specifically the lack of the [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-expose-headers) on the server side.

This happens when the Javascript code is in the browser is coming from a different host than the Bee node (or a different port in case of localhost). If the server sends an `Access-Control-Expose-Headers` containing the `Content-Disposition` value, then this works without problem. In Safari it's possible to disable cross-origin restrictions easily, and when I disable then this also works. 

It would also work if the Bee node were serving the application. However because the test application is a React application and it expects to find the files at the root path (`/`) on the server it's not working correctly when served from Bee because the application can be found at `/bzz/<hash>/` instead. It would be possible to use an ENS name or put a reverse-proxy in forward of Bee but those required too much effort to test.

With that said I don't know what's the best way moving forward because I don't completely understand the security implications. 

One way is to somehow add the `Access-Control-Expose-Headers` header with `Content-Disposition` in it to the Bee node when it returns files (in case of `GET` methods to `/files` and `/bzz` endpoints). Maybe this could be enabled in dev mode only or to domains that are already specified in `--cors-allowed-origins`.

Another is to workaround the need for relying on the `Content-Disposition` header for determining the filename. For example in the case of the `/files` endpoint if we don't find the header we could return with the hash as the name and in the case of the `/bzz` we could append the path to the hash and replace the path separator characters. This could be quite hacky with nasty edge-cases and also it would break the immutability of the content because based on where you query the data you could get back different results.

There may be other options (for example we say that this works as expected and won't fix) that is worth investigating. What do you think?

@nugaon

**Comment by nugaon** [comment]
> We even have a test for this case but the lesson is that we should somehow run these tests in the browser as well to make sure they really work.

There is possibility to run tests in browser context as I made some example in [test/bee-class.browser.spec.ts](https://github.com/ethersphere/bee-js/blob/master/test/bee-class.browser.spec.ts).

> It would also work if the Bee node were serving the application. However because the test application is a React application and it expects to find the files at the root path (/) on the server it's not working correctly when served from Bee because the application can be found at /bzz/<hash>/ instead. It would be possible to use an ENS name or put a reverse-proxy in forward of Bee but those required too much effort to test.

It is a different problem, but this is our next big issue that we have to solve in the future. From that you listed, the reverse-proxy solution would be really nice to have, to map the hash of the requested content to subdomain under the node host address (which is also good to use web2 security context). We can also create workaround for webpack to substitute references starting with '/' in html files, in order to load own content resources.

> With that said I don't know what's the best way moving forward because I don't completely understand the security implications.

it is a big research work for us, currently open BZZ URLs from unknown source is surely not secure, we need at least the before mentioned subdomain reverse-proxy for that, but would be even better to start working on real web3 protocols which solve its own security concerns, because the former only a hack to utilize already existing host-based solutions of web.

> One way is to somehow add the Access-Control-Expose-Headers header with Content-Disposition in it to the Bee node when it returns files (in case of GET methods to /files and /bzz endpoints). Maybe this could be enabled in dev mode only or to domains that are already specified in --cors-allowed-origins.

I suggest the latter.

> (...) in the case of the /files endpoint if we don't find the header we could return with the hash (...)

I think we shouldn't hack it like that, on Bee client side could be exposed this header where it is necessary

**Comment by vojtechsimetka** [comment]
Thinking about this some more, missing `content-disposition` header, or not finding a filename in this header, should never throw an exception and prevent downloading the content. Instead we should have some mechanism that tells the user the filename could not be retrieved so that they can somehow react to that.
