### ISSUE TITLE
file upload not working

### ISSUE THREAD

**Issue by savage9309** [ethersphere/bee-js#870]
i think bee-js file upload is not working. i cloned the ethersphere/examples-js and updated the bee-js to 6.4.0. 
when i use the upload-react i get a bzzHash but if i try to open via browser the file/image is not found. 
but it is working via swarm-desktop fileupload.
<img width="1426" alt="Screenshot 2023-09-08 at 11 28 22" src="https://github.com/ethersphere/bee-js/assets/98817986/a4c5e84d-ed56-4e30-826a-1585befbdbd2">

**Comment by dlaxcess** [comment]
Hi, I have the same issue.
It appears that the problem started with version 6.0.0 due to the change in the http library.
When I revert to version 5.2.0, everything works.

Here is the code I'm using in a Svelte environment:
```typescript
import { Bee, FileUploadOptions } from "@ethersphere/bee-js";
import { DEFAULT_NAME } from "@lib/common/config";
import { swarmApiEndpoint, swarmApiKey, SWARM_ZERO_APIKEY } from "@lib/nft/storage/swarm";

const getBee = (nodeUrl: string): Bee => {
  return new Bee(nodeUrl);
};

const swarmUploadFile = async (file: File | string): Promise<string> => {
  const nodeUrl = swarmApiEndpoint();
  const batchId = swarmApiKey();

  const bee: Bee = getBee(nodeUrl);

  const isFile = file instanceof File;

  console.log("FILE : ", file);

  const options: FileUploadOptions = {};
  options.pin = true;
  if (isFile && file?.size > 0) options.size = file.size;
  if (isFile && file?.type) options.contentType = file.type;

  const result = await bee.uploadFile(
    batchId,
    file,
    isFile ? file.name : DEFAULT_NAME,
    options
  );

  return result.reference;
};

export { swarmUploadFile };
```
This appears at page load
![Capture d’écran du 2023-09-23 17-00-59](https://github.com/ethersphere/bee-js/assets/35979307/30429413-53f2-45db-ac4c-0127d0af1d38)

and here is i get after upload:
![Capture d’écran du 2023-09-23 17-14-41](https://github.com/ethersphere/bee-js/assets/35979307/e7d483d7-1a74-4671-9ffd-fbd20d250dd6)

**Comment by rampall** [comment]
@savage9309 @dlaxcess can you try the latest [bee-js v6.7.4](https://github.com/ethersphere/bee-js/releases/tag/v6.7.4) and see if this issue persists.

**Comment by dlaxcess** [comment]
Oh it works much better now :)
Still have this error in console : `Refused to set unsafe header "content-length"` but it seems that it doesn't prevent the upload.
Thx
